# =============================================================
# APLICACIÓN
# =============================================================
spring.application.name=MicroTrazabilidad
server.port=8084

# =============================================================
# BASE DE DATOS (MongoDB)
# =============================================================
spring.data.mongodb.uri=mongodb://admin:admin123@localhost:27017/trazabilidaddb?authSource=admin
spring.data.mongodb.database=trazabilidaddb

# =============================================================
# LOGGING
# =============================================================
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# =============================================================
# JWT
# =============================================================
jwt.secret=ZmFrZUtleU1pY3JvdXN1YXJpb1ByYWdtYTIwMjU2Nzg5MDEyMzQ1Ng
jwt.expiration=3600000
